### ISSUE TITLE
Center align the "latest updates" section

### ISSUE THREAD

**Issue by shrayasr** [PySangamam/website#43]
Current: 

![image](https://user-images.githubusercontent.com/240368/39852776-064b8fb8-543c-11e8-93ae-d0ee5849b6cf.png)

I think this needs to be center aligned?

**Comment by syedjafer** [comment]
I made it by extending the width of twitter feed to 520px . Since height of both blog and twitter feed are same . only they differ by width . After changes the margin on left and right are both to be same . 
![screenshot from 2018-05-16 16-50-04](https://user-images.githubusercontent.com/20949510/40114119-56dcb8ca-5929-11e8-847c-6af415c0dd83.png)

The Margin , 
![screenshot from 2018-05-16 16-47-10](https://user-images.githubusercontent.com/20949510/40114134-67add68e-5929-11e8-9353-77163f6cd191.png)

In Mobile View , 
![screenshot from 2018-05-16 17-32-36](https://user-images.githubusercontent.com/20949510/40115792-379230b6-592f-11e8-9e78-32c8bfc82581.png)

**Comment by shrayasr** [comment]
LGTM 👍  Please push?

**Comment by syedjafer** [comment]
Pushed to master

**Comment by shrayasr** [comment]
> Pushed to master

Sorry, which master? I meant create a PR with it.

**Comment by astronomersiva** [comment]
I am back guys, sorry for the delay with everything...was unwell for the last few days.

@syedjafer the proper fix for this needs to be setting a `max-width` on the blog roll. With your current fix, it will break again when zoomed out further(as in, in larger displays). I will fix this myself.

Created a PR for this - #47 .

@syedjafer please refrain from pushing to protected branches like gh-pages and master directly.

**Comment by syedjafer** [comment]
:thumbsup:
